version: "3.1"
services:
  nginx:
    container_name: ic-nginx
    build:
      args:
        - CERTBOT_EMAIL=${IC_IT_EMAIL}
        - DOMAIN_LIST=va-chercher.com
      context: ./docker/nginx
      network: host
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./config/nginx:/etc/nginx/conf.d
    depends_on:
      - backend
      - frontend
    networks:
      - ic-net

  mongo:
    container_name: ic-mongo
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${IC_DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${IC_DB_PWD}
      MONGO_INITDB_DATABASE: icdb
    volumes:
      - ~/IC/DB:/data/db
    expose:
      - 27017
    networks:
      - ic-net

  mongo-express:
    container_name: ic-mongo-express
    image: mongo-express
    restart: always
    expose:
      - 8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${IC_DB_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${IC_DB_PWD}
      ME_CONFIG_BASICAUTH_USERNAME: ${IC_DB_USER}
      ME_CONFIG_BASICAUTH_PASSWORD: ${IC_DB_PWD}
    depends_on: 
      - mongo
    networks:
      - ic-net
  
  backend:
    container_name: ic-backend
    restart: always 
    build: 
      context: .
      dockerfile: docker/backend/Dockerfile
      network: host
    expose:
      - 3000
    environment:
      DATABASE: ${DATABASE}
      USERNAME: ${USERNAME}
      PASSWORD: ${PASSWORD}
      FULLNAME: ${FULLNAME}
      EMAIL: ${EMAIL}
      ROLE: ${ROLE}
      PORT: ${PORT}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRES_IN: ${JWT_EXPIRES_IN}
    links:
      - mongo
    depends_on:
      - mongo
    networks:
      - ic-net
    
  frontend:
    container_name: ic-frontend
    restart: unless-stopped
    build:
      context: .
      dockerfile: docker/frontend/Dockerfile
      network: host
    expose:
      - 80
    networks:
      - ic-net
    
networks:
  ic-net:
